version: '3.8'

services:
  microservice1:
    build:
      context: ./microservice-authentification
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
