version: '3.8'

services:
  authentification:
    build:
      context: ./microservice-authentification
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  booking:
    build:
      context: ./microservice-booking
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  listing:
    build:
      context: ./microservice-listing
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - microservices-network

  tracking:
    build:
      context: ./microservice-tracking
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - microservices-network

  user_management:
    build:
      context: ./microservice-user_management
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
