spring:
  application:
    name: microservice-authentification
    datasource:
      url: jdbc:mysql://localhost:3306/my_db_name
      username: user
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081